import Image from 'next/image'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {children}
        </div>

        <img src="/Turkey.jpg" alt="ロゴ" style={{ position: 'absolute', top: '10px', left: '10px' }} /> 
        <img src="/Turkey.jpg" alt="中央の画像" style={{ display: 'block', margin: 'auto' }} />

      </body>
    </html>
  );
}